language: node_js
node_js:
    - '12'
install:
    - npm install
script:
    - npm run build
after_script:
  - ls
  - git add .
  - git commit -m "aimin edit"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}"
